# travis

language: generic
sudo: false
dist: trusty

before_install:
  - bash --version
  - openssl version

script:
  - |
      bash --posix ./create-root-ca -d travis-ca <<EOF
      travis-ca
      bogus.com
      US
      California
      San Francisco
      Bogus Inc.
      Operations
      Bogus Inc. Certificate Authority
      rootCA_password
      rootCA_password
      EOF
  - cd travis-ca/
  - |
      bash --posix ./bin/create-signing-ca -d travis-signing << EOF
      travis-signing
      bogus.com
      US
      California
      San Francisco
      Bogus Inc.
      Operations
      Bogus Inc. Certificate travis-signing
      signCA_password
      signCA_password
      rootCA_password
      EOF
  - cd travis-signing/
  - |
      bash --posix ./bin/create-server -s travis-server.bogus.com -a 0.0.0.0 -a 1.1.1.1 << EOF
      US
      California
      San Francisco
      Bogus Inc.
      Jurisdiction of travis-server.bogus-com
      travis-server.bogus.com
      signCA_password
      EOF
  - |
      bash --posix ./bin/create-client -c travis-client << EOF
      US
      California
      San Francisco
      Bogus Inc.
      private
      travis-client
      travis-client@bogus.com
      signCA_password
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/travis-server-bogus-com.server.crt << EOF
      1
      y
      signCA_password
      EOF
  - |
      bash --posix ./bin/revoke-cert -c certs/travis-client.client.crt << EOF
      5
      y
      signCA_password
      EOF
